---
output: pdf_document
---

#Unix introduction

Unix is a Swiss knife for working with big amounts of data. This tutorial shows a practical usage of the UNIX command line `bash` with emphasis on explanation of mechanisms and logic behind. More materials about UNIX and `bash` in particular you can find all over the internet, I will just mention two : [software carpentry UNIX tutorial](http://swcarpentry.github.io/shell-novice/) for very basics and [Advanced Bash-Scripting Guide](http://tldp.org/LDP/abs/html/index.html) as a complete reference to bash scripting.

## Syntax of this exercise

* The comment symbol of bash is `#`, everything after this symbol is ignored.
* Blocks of code will be in boxes, note also the usual syntax of bash commands: `command -parameters location`.

```bash
ls -h / # list files and directories in -human readable format located at root directory
```

* Anything in `< >` you have to replace by meaningful paths, file names or parameters.

```bash
ssh <username>@prd.vital-it.ch # this will be written in this document
ssh kjaron@prd.vital-it.ch # this is example, how it can be used
```

* Bash commands are (usually) meaningful acronyms, the explanation is written after every first occurrence in brackets.
* Some quantitative tasks have correct answers in brackets. Example: How many lines are in the file `file.txt`? [42]
* Detailed explanations will be written in blocks as follows:

<sub>These explanatory blocks should help you to understand. So, every time you feel confused, read these blocks. If it deosn't answer your question, then ask.</sub>

## Getting started

Unix is a type of operating system, to communicate with the operating system we will use a command line language called `bash`.
Just like natural languages, computer languages have their own syntax and vocabulary.
This class is technically just an introduction to a new language.

The very first step is to open a terminal.

***

\newpage

## Open terminal and get to cluster

How to get to the cluster will be dependent on what operating system you use.

### Windows users

1. Install [WinSCP](http://winscp.net/eng/download.php) and [Putty](http://www.chiark.greenend.org.uk/~sgtatham/putty/download.html)
2. First start WinSCP by:
    -	hostname: prd.vital-it.ch
    -	username:
    -	password:
3. Then start your Putty by entering the hostname: prd.vital-it.ch

<sub>
The programs mentioned above will allow you to log onto the cluster.
If you would like to have standard unix tools on your computer,
you can use the beta version of Linux subsystem on Windows 10 (see [this tutorial](https://www.howtogeek.com/249966/how-to-install-and-use-the-linux-bash-shell-on-windows-10/)) or you can install [cygwin](http://www.cygwin.com/), a collection of unix tools adopted for windows.
</sub>

### Linux / OS X users

Open a terminal.

 - common Linux systems: Press `ctrl + alt + t`
 - Mac OS X: press `cmd + space` to start a spotlight search, then type `terminal`. This should find the terminal app therefore you can just hit `enter` to launch it.

If you managed to open a terminal window, connect to Vital-it using `ssh` (secure shell).

```bash
ssh <username>@prd.vital-it.ch
```

You will be asked to type a password.

***

\newpage

## Bash as explorer

You should see a command line in front of you.
You can use `bash` to manipulate files just like in a file browser.
You do not have to be scared to explore on Vital-it,
it is not a problem to restore your cluster account to the default setting anytime.

### Browsing directories

1. Go to your home directory `/home/<user_name>` and check the content using `ls` (list segments). You will probably see nothing (i.e. your home is empty).
2. Make a new directory, enter the directory:

```bash
mkdir SAGE
cd Sage
```

<sub>
Everything in UNIX is case sensitive, i.e. the name Sage is not the same as SAGE. Therefore the error message you see `cd: Sage: No such file or directory`. Error messages are usually very precise in what is wrong and the vast majority of problems are caused by the execution of a command in the wrong directory.
</sub>

3. Use `pwd` (print working directory) to check your location.
4. Correct the command to enter the directory `SAGE`.
5. Use `pwd` to check your location.
6. Go to the parent directory `cd ..` (change directory) and verify the success using `pwd` command again. Generally, `cd` changes a working directory to the provided path `cd <path>`.

<sub>Meanings of symbols are as follows: `.` is a current directory, `..` is a parent directory, `/` is a root directory, `~` is your home directory. Note that the symbol `~` carries a different path for every user: `/home/<username>` and symbols `.` and `..` carry different paths in every single directory, hence a path specified using one of these two symbols is called relative path. The command `cd` (change directory) and correct handling of paths is essential for everything done in the Unix terminal. The path can be defined relative to your current directory (ex: `cd ./SAGE` or `cd ..`) or absolutely, i.e. starting from the root directory of the computer (ex: `cd /home/kjaron`). </sub>

### Copy, move, rename and remove

1. Copy the directory `/scratch/beegfs/monthly/mls_2018/UNIX_testfiles` to your working directory using command `cp` (copy)

```bash
cp -<parameters> <path/file> <path/new_file_name> # generally
cp -r /scratch/beegfs/monthly/mls_2018/UNIX_testfiles .
```

<sub> If you want to copy and retain the original name, you can specify just a path.
If you want to copy a file (or directory) to the working directory you are in,
you can just write only `.`.
Do you know why you have to specify `-r` to copy a directory? You can take a look in the manual (`man cp`). </sub>

2. Go inside and check the content of the directory (you should know how, if you don't, scroll up).
3. Copy file `browsing.txt` in the directory `nonemptydir`. Do you need the parameter `-r`? If you are not sure, check again the manual page.
4. Go to `nonemptydir`, rename `browsing.txt` to `<your_new_name>.txt` and move the renamed file to `UNIX_testfiles`.

```bash
cd ./nonemptydir
mv browsing.txt <your_new_name>.txt
mv <your_new_name>.txt ..
cd ..
```

5. What is the difference between the second and third lines? Can you figure out how to do the same without changing the directory to `nonemptydir`?

<sub>The command `mv` (move) moves file to the given path and renames it to the given name. So, if the `<path_to_input>` is the same as `<path_to_output>` in the command</sub>

```bash
mv <path_to_input>/<file_name> <path_to_output>/<new_file_name>
```

<sub>, the file will be only renamed. If the path is different, but `<new_file_name>` is not provided, the file will be just moved (not renamed).</sub>

6. Remove the copied and renamed file.

```bash
rm <your_new_name>.txt
```

7. Try to remove the directory `nonemptydir`. Could you figure out why `rm <dir>` or `rmdir <dir>` is not working?

<sub> The command `rm` is to remove files, `rmdir` is to remove empty directories. If you want to remove a directory with files inside, you have to specify the parameter `-r` (recursive) : `rm -r <dir_to_delete>`. However, be careful, there is nothing like "Trash" in the bash, i.e. what is deleted is permanently lost! </sub>

8. Try the command `man <command>` (manual) to show the manual page of some commands. What does the `-a` mean in the `ls` command? Could you use this parameter to find out why `rmdir` is not working on `nonemptydir`, even through `ls` is not showing any files inside?

***

## Break!!!

\newpage

## More than explrorer

`bash` can be used also for reading text files and manipulating them. The `bash` tools are very optimized, therefore they work on huge files which will come handy once your file will be a genome.

### Commands text processing

There are many many ways to look at a plain text file in the terminal, so if you find other solutions than what we provide, do not wonder. Some of commands for text processing:

- Commands `head -n <num_of_lines> <text_file>` and `tail -n <num_of_lines> <text_file>` print the beginning (first n lines) and the end of input files (last n lines), respectively.
- Command `less <text_file>` will allow to browse a text file (of any size). You can use scroll or use arrows to browse the file. If you press `q` (for quit), you will escape back to the terminal. If you want to explore, `less` is a very good tool.
- Command `wc -lwc <text_file>` (word count) counts the number of lines (`l`; in fact it's newline characters), words (`w`) and characters (`c`) in an input file. You can specify what to compute by changing the parameters.
- Command `tr -d '<character_to_be_removed>' <text_file>` (translate characters) can delete all occurrences of a given character.

1. Working with the file `browsing.txt`, use the commands `head -n <num_of_lines> <text_file>`, `tail -n <num_of_lines> <text_file>` and `cat <text_file>` (concatenate) to see the beginning, the end, or the whole file, respectively. How many lines are in the file?
2. Use `less <text_file>` to check `AllIllumina-PEadapters.fa`. You can use scroll or arrows to move in the file. If you press `q`, you will escape back to the terminal. You can also use `head` and `tail` commands to see the beginning and the end of the file.
3. To get an idea about the file, you can use the command `wc` (word count), which counts the number of newline characters, words and characters in the input file. You can specify output by parameters. How many lines are in `browsing.txt`?

Command `grep` searches the file and prints all lines containing a pattern specified by a parameter: `grep <pattern> <file.txt>`. I heavily recommend to write such patterns in quotes "", because some characters have a special meaning in the command line (for example white spaces, or the symbols ">", "|", ".", "\\", etc.).

4. Explore the behaviour of `grep` by selecting different lines in file `browsing.txt`. Example:

```bash
grep "to check" browsing.txt
```

One of the most powerful and simple tools for reading text files in terminal is `less`. It loads to memory only parts of opened file that are read, therefore you can use this tool to check a file of any size (even files exceeding RAM of your computer). To browse file you can use arrows, page-up/down or scroll of a mouse.

5. Look at the `sample.fasta` file using `less <file_to_read>`

### Pipes

The output of commands is usually printed to the terminal (lists of files when using `ls`, content of file when using `cat`, etc.). You can use the symbol `|` to redirect ("pipe") the standard output as an input to another command. We can use a few commands to find out how many Illumina adapters are in the file `AllIllumina-PEadapters.fa`. File `AllIllumina-PEadapters.fa` is a fasta file, so every sequence is represented by a header line starting by symbol ">" and the sequence itself.

1. How many adapters are saved in the file `AllIllumina-PEadapters.fa`? [22]

```bash
grep ">" AllIllumina-PEadapters.fa | wc -l
```

To redirect an output to a file rather than to other command, you can use the symbol `>`. Be careful, if the target file exists, it will be overwritten. To add lines to the end of the file, you can use `>>` (= concatenate).

Using the same tools we can answer various questions. Another example of usage is to compute the number of nucleotides in simple fasta.

2. How many nucleotides are in the file `sample.fasta`? [64570] Hint: check `-v` argument of grep.

<sub>
If you ended up on number 66719 you have counted newline characters as nucleotides. You can either count them by `wc -l` or you can use the trick described at task 4.
</sub>


3. You can also solve this problem by using the command `tail` which can also print all but a given number of skipped lines from the beginning: `tail -n +<number_of_the_first_line_to_be_printed> <file>`. The following command prints the number of characters:

```bash
tail -n +2 sample.fasta | wc -c
```

However, this command shows the number of characters (newline characters included). It is not entirely correct.

4. We can use the `tr` (translate characters) command to delete all newline characters before you count them using `wc`. Note how the commands are nested, you can use as many pipes as you need.

```bash
tail -n +2 sample.fasta | tr -d '\n' | wc -c
```

<sub>
There are many ways how to read or edit plain text files using command line tools. Next to the presented commands, there are several scripting languages specialized for text processing like `awk` or `sed` or `grep`. In bioinformatics is also common to use `biopython` or `BioPerl` to work with fasta and fastq files.
</sub>


Programs have two "channels" to produce messages for the user : standard output stream (stdout) and standard error stream (stderr). Usually stdout prints results (Example: list of files is result of command `ls`) and stderr usually prints errors (Example: file or directory does not exist in `ls <path>`).
Pipes are redirecting the standard output stream,
the standard error stream is still printed to terminal.

5. Try to type a command that produces both errors and output, as well as redirects the output to another program. For instance `ls non_existing_file sample.fasta | wc -w` should do the job. Could you say what is the error message produced by `ls` and the output produced by `wc -w`?

<sub>
The file `non_existing_file` does not exist, therefore the error message on the error stream.
However `sample.fasta` does, therefore `ls` will list the name of the file to the output stream (and thus `wc -w` reports one word).
</sub>

To redirect an output stream to a file instead of anther program you can use `<command> > <file>`.
If `<file>` exists, it's going to be replaced (yes, it's dangerous!).
You can as well append the output stream to the end of an existing file by `<command> >> <file>`.
To redirect the error stream use `2>` and to redirect both output and error stream use `&>`.

6. Try to use the command from the previous task to produce some messages on both streams and explore how `>`, `>>`, `&>` work. Clean the files you create afterwards.

## Challenges

1. Extract all header lines of `AllIllumina-PEadapters.fa` file to separated file. If you do the same on `sample.fasta`, how many headers you extract?

```{bash echo=FALSE, eval=FALSE}
grep ">" AllIllumina-PEadapters.fa > adapter_headers.txt
wc -l adapter_headers.txt
```

2. Compute the total length of low-complexity nucleotides (lower-case letters, i.e. non-capital letters) in `sample.fasta` [15754].

```{bash echo=FALSE, eval=FALSE}
grep -v ">" sample.fasta | sed 's/[A-Z]//g' | tr -d '\n' | wc -c
```

3. Command `touch` will modify a time of last modification of a file. Find a way to touch all your files, and verify the success using `ls -l`. Pro tip: Use google to find an answer and manual to understand it.

```{bash echo=FALSE, eval=FALSE}
find . -exec touch {} \;
```

<sub>There are loads of different solutions. One of them can be found in [the source code for this document online](https://github.com/KamilSJaron/Sequence-a-genome/blob/master/2018_autumn/1_unix_basics/1_unix_basics_ex.Rmd#challenges) <sub\>

***

## Tips and tricks

- Command `cd` without any argument changes the working directory to your home. Symbol `~` works the same, it is symbol of home.
- Press tabulator to call whisperer (auto completion) every time you are writing a path. It is handy with long file names as we can find in genomics. Note that you will have to type all the first letters of the file which are in common with other file names of same the directory before auto completion can be achieved by pressing tabulator. It is a good way to prevent typos, because an auto completed path is usually valid.
- Arrows up and down allows for browsing your command history saved at `~/.bash_history`
- Press `Ctrl+R` for a full text search in the command history
- Press `Ctrl+C` to stop the running process, useful if you use `cat` on a huge file to stop seeing text flowing endlessly... Beware to remove result/temporary files created by the program if you use `Ctrl+C` to stop a running program, otherwise there may be conflicts the next time you run the same program.
- You can use wild characters `?`, `[]` and `*`, to specify a group of files. `?` stands for any single character, `[XYZ]` one of the specifies characters (XYZ in this case, you can also use numbers), `*` any number of any characters. See examples

```bash
cat *.txt # prints all text files
ls ?? # lists all files or directories with exactly two letter names
cp /<path>/LS[1234]* . # copiing all files staring by LS1 LS2 LS3 or LS4 from given <path>
```

***

Ask me a question! Contact: kamiljaron@gmail.com
